### ISSUE TITLE
java.lang.NegativeArraySizeException when using JLayer/MP3SPI

### ISSUE THREAD

**Issue by nhydock** [JorenSix/TarsosDSP#71]
When trying to use the desktop lib of TarsosDSP with JLayer as my mp3 decoder, it gives this error.  It's because JLayer defines its frameSize value (returned in format.getFrameSize() line 199 of AudioDispatcher) as -1 (AudioSystem.NOT_SPECIFIED)

Output from when I try running the FeatureExtractor program as an example
```
Exception in thread "main" java.lang.NegativeArraySizeException
	at be.tarsos.dsp.AudioDispatcher.setStepSizeAndOverlap(Unknown Source)
	at be.tarsos.dsp.AudioDispatcher.<init>(Unknown Source)
	at be.tarsos.dsp.io.jvm.AudioDispatcherFactory.fromFile(Unknown Source)
	at FeatureExtractor$BeatExtractor.run(FeatureExtractor.java:365)
	at FeatureExtractor.checkArgumentsAndRun(FeatureExtractor.java:81)
	at FeatureExtractor.<init>(FeatureExtractor.java:63)
	at FeatureExtractor.main(FeatureExtractor.java:130)
```

**Comment by JorenSix** [comment]
Hi,

Thanks for the bug report. I think this is related to a previous bug report. Could you test the latest version using the ComplexOnsetDetector in the beat extractor?
