### ISSUE TITLE
ffmpeg for cortex a-53?

### ISSUE THREAD

**Issue by Barganax** [JorenSix/TarsosDSP#73]
Hi,

I guess I should have gone to the ffmpeg project, but I'm not absolutely sure this is the problem.  I have a moto g3, which has a cortex a-53 cpu (armv8).  I need an AudioDispatcher for a file.  I tried new AndroidFFMPEGLocator(this); but it couldn't find one.  Am I just screwed?

**Comment by lao100** [comment]
I get the same problem.
error: java.lang.String be.tarsos.dsp.io.android.AndroidFFMPEGLocator$CPUArchitecture.name()' on a null object reference

**Comment by Barganax** [comment]
I'm using studio - these are the messages I got:

2-29 09:32:29.657 6865-6865/net.pictnet.marigold.soundchunker I/art: Late-enabling -Xcheck:jni
02-29 09:32:29.754 6865-6865/net.pictnet.marigold.soundchunker D/AndroidFFMPEGLocator: CPUINFO line: processor	: 0
02-29 09:32:29.754 6865-6865/net.pictnet.marigold.soundchunker D/AndroidFFMPEGLocator: CPUINFO line: model name	: ARMv7 Processor rev 0 (v7l)
02-29 09:32:29.754 6865-6865/net.pictnet.marigold.soundchunker D/AndroidFFMPEGLocator: CPUINFO line: BogoMIPS	: 38.40
02-29 09:32:29.754 6865-6865/net.pictnet.marigold.soundchunker D/AndroidFFMPEGLocator: CPUINFO line: Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 evtstrm 
02-29 09:32:29.754 6865-6865/net.pictnet.marigold.soundchunker I/AndroidFFMPEGLocator: Detected Native CPU Architecture: ARMEABI_V7A_NEON
02-29 09:32:29.757 6865-6865/net.pictnet.marigold.soundchunker W/System.err: java.io.FileNotFoundException: armeabi-v7a-neon_ffmpeg
02-29 09:32:29.761 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
02-29 09:32:29.761 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:313)
02-29 09:32:29.761 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:287)
02-29 09:32:29.761 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at be.tarsos.dsp.io.android.AndroidFFMPEGLocator.unpackFFmpeg(Unknown Source)
02-29 09:32:29.762 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at be.tarsos.dsp.io.android.AndroidFFMPEGLocator.<init>(Unknown Source)
02-29 09:32:29.762 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at net.pictnet.marigold.soundchunker.MainActivity.onCreate(MainActivity.java:35)
02-29 09:32:29.762 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at android.app.Activity.performCreate(Activity.java:6010)
02-29 09:32:29.762 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
02-29 09:32:29.762 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
02-29 09:32:29.762 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
02-29 09:32:29.762 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:155)
02-29 09:32:29.762 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
02-29 09:32:29.762 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-29 09:32:29.762 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at android.os.Looper.loop(Looper.java:135)
02-29 09:32:29.762 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5343)
02-29 09:32:29.762 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-29 09:32:29.762 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
02-29 09:32:29.762 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
02-29 09:32:29.762 6865-6865/net.pictnet.marigold.soundchunker W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
02-29 09:32:29.762 6865-6865/net.pictnet.marigold.soundchunker I/AndroidFFMPEGLocator: Ffmpeg binary location: /data/data/net.pictnet.marigold.soundchunker/cache/ffmpeg is executable? false size: 0 bytes
02-29 09:32:29.867 6865-6885/net.pictnet.marigold.soundchunker D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
02-29 09:32:29.875 6865-6865/net.pictnet.marigold.soundchunker D/Atlas: Validating map...
02-29 09:32:29.917 6865-6885/net.pictnet.marigold.soundchunker I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build:  (Ibddc658e36)
                                                                             OpenGL ES Shader Compiler Version: E031.25.03.04
                                                                             Build Date: 08/10/15 Mon
                                                                             Local Branch: workspace
                                                                             Remote Branch: 
                                                                             Local Patches: 
                                                                             Reconstruct Branch: 
02-29 09:32:29.919 6865-6885/net.pictnet.marigold.soundchunker I/OpenGLRenderer: Initialized EGL, version 1.4
02-29 09:32:29.934 6865-6885/net.pictnet.marigold.soundchunker D/OpenGLRenderer: Enabling debug mode 0
02-29 09:33:17.299 6865-6865/net.pictnet.marigold.soundchunker I/System.out: Running on Android!
02-29 09:33:17.300 6865-6865/net.pictnet.marigold.soundchunker E/PipeDecoder: Could not find an ffmpeg binary for your Android system. Did you forget calling: 'new AndroidFFMPEGLocator(this);' ?
02-29 09:33:17.300 6865-6865/net.pictnet.marigold.soundchunker E/PipeDecoder: Tried to unpack a statically compiled ffmpeg binary for your architecture to: /data/data/net.pictnet.marigold.soundchunker/cache/ffmpeg
02-29 09:33:17.300 6865-6865/net.pictnet.marigold.soundchunker D/AndroidRuntime: Shutting down VM
02-29 09:33:17.309 6865-6865/net.pictnet.marigold.soundchunker E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: net.pictnet.marigold.soundchunker, PID: 6865
                                                                                 java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                                     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:275)
                                                                                     at android.view.View.performClick(View.java:4785)
                                                                                     at android.view.View$PerformClick.run(View.java:19884)
                                                                                     at android.os.Handler.handleCallback(Handler.java:746)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
                                                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:270)
                                                                                     at android.view.View.performClick(View.java:4785) 
                                                                                     at android.view.View$PerformClick.run(View.java:19884) 
                                                                                     at android.os.Handler.handleCallback(Handler.java:746) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702) 
                                                                                  Caused by: java.lang.Error: Decoding via a pipe will not work: Could not find an ffmpeg binary for your system
                                                                                     at be.tarsos.dsp.io.PipeDecoder.<init>(Unknown Source)
                                                                                     at be.tarsos.dsp.io.PipedAudioStream.<clinit>(Unknown Source)
                                                                                     at be.tarsos.dsp.io.android.AudioDispatcherFactory.fromPipe(Unknown Source)
                                                                                     at net.pictnet.marigold.soundchunker.ChunkingWriterProcessor.findOnsets(ChunkingWriterProcessor.java:219)
                                                                                     at net.pictnet.marigold.soundchunker.ChunkingWriterProcessor.access$000(ChunkingWriterProcessor.java:32)
                                                                                     at net.pictnet.marigold.soundchunker.ChunkingWriterProcessor$MiniWriterProcessor.processingFinished(ChunkingWriterProcessor.java:166)
                                                                                     at be.tarsos.dsp.AudioDispatcher.stop(Unknown Source)
                                                                                     at net.pictnet.marigold.soundchunker.MainActivity.stopChunking(MainActivity.java:104)
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:270) 
                                                                                     at android.view.View.performClick(View.java:4785) 
                                                                                     at android.view.View$PerformClick.run(View.java:19884) 
                                                                                     at android.os.Handler.handleCallback(Handler.java:746) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702) 
02-29 09:33:19.819 6865-6865/net.pictnet.marigold.soundchunker I/Process: Sending signal. PID: 6865 SIG: 9

**Comment by lao100** [comment]
chechk  the assets folder should contain these binaries:
 * <ul><code>assets/x86_ffmpeg</code> for x86</ul>
 * <ul><code>assets/armeabi-v7a_ffmpeg</code> for armeabi-v7a</ul>
 * <ul><code>assets/armeabi-v7a-neon_ffmpeg</code> for armeabi-v7a-neon</ul>

**Comment by Barganax** [comment]
No, app/build/intermediates/assets contains 2 directories, androidTest and debug.  debug is empty.   AndroidTest has an empty debug directory - that's all.

**Comment by Barganax** [comment]
Ok, I fixed it by renaming the ffmpeg executable and putting it in /app/build/intermediates/assets/debug.  I'm sorry but this wasn't at all obvious.

**Comment by JorenSix** [comment]
Hi,

It is not the best documented part of TarsosDSP or Android Studio, it also seems to change often. If anybody is willing to create working sample application please be my guest...

Regards

Joren

**Comment by NickDGreg** [comment]
Hi, 
Would you be able to elaborate on how this issue was solved? 
I am also attempting to use the TarsosDSP library in an android app to perform a pitch analysis on a wav file and as suggested in [this](http://0110.be/posts/Decode_MP3s_and_other_Audio_formats_the_easy_way_on_Android) post from Joren I use the line  
`new AndroidFFMPEGLocator(this);` 
However, I receive the error:
FATAL EXCEPTION: main
java.lang.NoSuchFieldError: android.os.Build.SUPPORTED_ABIS
at be.tarsos.dsp.io.android.AndroidFFMPEGLocator.getCPUArchitecture(Unknown Source)
at be.tarsos.dsp.io.android.AndroidFFMPEGLocator.<init>(Unknown Source)

(and there are more error messages but I thought these were the relevant ones) 

I have attempted to include the three ffmpeg files from the [TarsosDSP-static-ffmpeg/Android ](http://0110.be/releases/TarsosDSP/TarsosDSP-static-ffmpeg/Android/)directory in the /app/build/intermediates/assets/debug folder in my project based on Barganax's solution but that had no effect.

I also saw that Barganax mentioned they remnamed the ffmpeg executable but I wasn't sure which of the three files in the directory that was referring to and what that executable was renamed as.

I'd be grateful for any help and can supply more information if that could help find a solution.

regards, Nick

**Comment by Barganax** [comment]
Hi Nick,

Yeah, this was really frustrating.  I got an error but it said what file it was looking for so I renamed the file to that.  In the prebuilt-binaries directories are three subdirectories named for different architectures, each containing an ffmpeg executable.  You have to pick the one that matches your architecture and rename it appropriately - I had to rename it to armeabi-v7a-neon_ffmpeg.  And you don't put it in the assets directory like it says.  I put it in <App Name>/app/build/intermediates/assets/debug and it works for development.  Your error message looks different,
though.  It doesn't say that it couldn't find the file, but rather nosuchfield.  But aybe if you try this it will be happy.

Hope this helps.

**Comment by NickDGreg** [comment]
Hi, 
Thanks for the extra help. I tried to put the binaries in the assets/debug folder but that didn't manage to solve the problem. I'm not sure what to try now, but if I find something that helps or a new question I'll post it here.

**Comment by NickDGreg** [comment]
Just in case anyone is having a similar problem. I solved it by getting hold of a newer phone. I was originally using a 3 year old sony xperia. That had trouble with most of the Tarsos functions that I tried to use. Now using a new samsung the FFMPEGLocator works. 

Though I did have to put the three ffmpeg files into the /app/build/intermediates/assets/debug folder as described by barganax

**Comment by james-woo** [comment]
I also had similar issues (ffmpeg not being found), what I ended up doing, which worked for me was to put the three files in /app/build/intermediates/assets/ NOT in the debug folder.
