### ISSUE TITLE
 ConstantQ crashes with ArrayIndexOutOfBoundsException: 16384

### ISSUE THREAD

**Issue by neevek** [JorenSix/TarsosDSP#74]
I am trying to plot a spectrogram with the Constant-Q output produced by `ConstantQ.calculateMagintudes()`, but I do not know how to specify the parameters.

This is my code for creating the ConstantQ object:
```
    ConstantQ cq = new ConstantQ(44100, 30.703f, 15804.f, 36);
    float inBuf[] = new float[4410]; // 1/10 second of audio data
    // fill inBuf with samples
    ...
    // this line throws
    cq.calculateMagintudes(inBuf);
    float magBuf = cq.getMagnitudes();
```

Following is the stack trace:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 16384
	at be.tarsos.dsp.util.fft.FloatFFT.cftf1st(FloatFFT.java:5108)
	at be.tarsos.dsp.util.fft.FloatFFT.cftfsub(FloatFFT.java:4038)
	at be.tarsos.dsp.util.fft.FloatFFT.realForward(FloatFFT.java:353)
	at be.tarsos.dsp.util.fft.FloatFFT.realForward(FloatFFT.java:311)
	at be.tarsos.dsp.util.fft.FFT.forwardTransform(FFT.java:81)
	at be.tarsos.dsp.ConstantQ.calculate(ConstantQ.java:286)
	at be.tarsos.dsp.ConstantQ.calculateMagintudes(ConstantQ.java:312)
	at net.neevek.test.TestConstantQ.main(TestConstantQ.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

If I increase the buffer size to some big number like 100000 for the input, ConstantQ works and generates some magnitudes, even if it works this way, there's only a few dozen of magnitude groups generated. And it is strange that I can't control the length of the input data.

My question is how do I use this class to generate magnitudes, with which I can create a Constant-Q spectrogram?

P.S.: I guess `Magintudes` is a typo in the code.

**Comment by JorenSix** [comment]
Hi,

You correctly create a constantq object (with 36 bins per octave) but then the algorithm needs a certain amount of audio samples to calculate the constant q (using an FFT). This can be requested using the getFFTlength() method. So in pseudo code:

    ConstantQ q = new ConstantQ(44100, 30.703f, 15804.f, 36);
    int bufferLength = q.getFFTLenght();
    int overlap = q.getFFTLenght()/2;
    AudioDispatcher d = AudioDispatcherFactory.fromFile("yourfile.wav",bufferLength,overlap); 
    d.addAudioProcessor(q);
    d.addAudioProcessor(new AudioProcessor(){
        void process(AudioEvent e){
            q.getMagnitudes()//show or store the magnitudes
        }
    }
    d.run();

Regards

Joren

**Comment by JorenSix** [comment]
Hi, 

The size of the fft needed is determined by the minimum frequency you want to detect (30Hz in your case). So a very large fft is needed, which needs many samples so this determines how much the cte-q is calculated. 

 Try to increase the minimum frequency if your application allows this. Otherwise play with the step size.

Regards

Joren

**Comment by neevek** [comment]
Yes, I have increased minimum frequency and overlap, now the result is better.
