### ISSUE TITLE
startRecording() called on an uninitialized AudioRecord

### ISSUE THREAD

**Issue by meNESS** [JorenSix/TarsosDSP#93]
Hi,

I'm getting following exception while using following codes. I'm trying to run the app on an Emulator (API 23, SDK Build Tools 24). How can I fix that issue?

```java
AudioDispatcher dispatcher = AudioDispatcherFactory.fromDefaultMicrophone(8000, 1024, 0);

        PitchDetectionHandler pdh = new PitchDetectionHandler() {
            @Override
            public void handlePitch(PitchDetectionResult result, AudioEvent e) {
                final float pitchInHz = result.getPitch();
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        TextView view = (TextView) findViewById(R.id.textView);
                        view.setText(Float.toString(pitchInHz));
                    }
                });
            }
        };
        AudioProcessor p = new PitchProcessor(PitchProcessor.PitchEstimationAlgorithm.FFT_YIN, 8000, 1024, pdh);
        dispatcher.addAudioProcessor(p);
        new Thread(dispatcher, "Audio Dispatcher").start();
```

> Caused by: java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
>                                                                             at android.media.AudioRecord.startRecording(AudioRecord.java:885)
>                                                                             at be.tarsos.dsp.io.android.AudioDispatcherFactory.fromDefaultMicrophone(Unknown Source)
>                                                                             at io.github.meness.pitch.MainActivity.onCreate(MainActivity.java:22)

**Comment by omi90** [comment]
Please check if you have below permission set in android manifest.
<uses-permission android:name="android.permission.RECORD_AUDIO" />

**Comment by fraserjohnstone** [comment]
I have been having this exact issue. did you ever work out what was wrong?

**Comment by Charles808** [comment]
I solved this by using the Permission.

Please, be aware that if you are targeting Marshmallow or above you need to use the Runtime Permission.
Just write the permission in the Manifest won't be enough.

In my case, the easiest way is simply change the targetSdkVersion from gradle:app, below 23.

Wish you luck.

**Comment by wimmerb** [comment]
Hey Charles, 

I'm relatively new to Android development: what do you mean bei "Runtime Permission" i am currently trying this: which tells me I don't have permissions:

if (ContextCompat.checkSelfPermission(this, Manifest.permission.RECORD_AUDIO)
                != PackageManager.PERMISSION_GRANTED) {
            Log.d("jo", "nopermission"); }

but I can't figure out what to do about it.

(I put this in my manifest)
<uses-permission android:name="android.permission.RECORD_AUDIO" />

Thx for the help :)
